### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by hsgw** [okyeron/fates#10]
Hello.
I have designed a new PCB since yours seems to be unavailable.
I would like to use this installation script as a reference on my hardware, could you apply some kind of license?
thanks.

**Comment by okyeron** [comment]
There is no license. 

This repo is out of date and might not work properly. See my suggestion below.

Please understand - Fates is no longer available because Monome asked me to stop making it. As Fates is a norns "clone" this causes trouble for monome because of support issues and also undercuts the sales of the official norns shield - which monome sells to fund the development cost of the the open source norns software.

Suggestions:
- Start with one of the new norns disk images that was released this week and make modifications to that for your hardware. See https://github.com/monome/norns-image/releases/tag/220306
- If you do want to compile your own kernel, etc., then please use this repo only as reference and then create new scripts specific to your new hardware. 
- Please do not call your project "Fates" or anything using "Fates" in the title. This causes confusion and support issues for me.

**Comment by hsgw** [comment]
I' m trying to compile the kernel module with reference to this repository.
But I have missed new norns image supports rpi4.
It seems easier to use it, so I will try.

Thank you for sharing your advice with me.

> Please do not call your project "Fates" or anything using "Fates" in the title. This causes confusion and support issues for me.

Of course, I would make sure not to cause any inconvenience.
